# SPDX-License-Identifier: GPL-2.0-only
# Kenshi - Lo-Fi Games. Ported from Vortex's game-kenshi. Mods live under mods/
# and MUST sit in mods/<name>/<name>.mod, where <name> matches the .mod file's
# base name. game.lua rebuilds that per-mod folder at install time (as Vortex's
# installer does); without it, the applier's wrapper-hoisting would flatten the
# very folder the game needs to load the mod.
api_version    = 2
id             = "kenshi"
name           = "Kenshi"
steam_appid    = 233860
nexus_domain   = "kenshi"
mod_root       = "mods"
deploy         = "link"
install_probe  = ["steam"]
required_files = ["OgreMain_x64.dll", "data/kenshi.ico"]
