# SPDX-License-Identifier: GPL-2.0-only
[package]
name = "modrix-gui"
description = "Modrix graphical frontend (Iced)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "modrix-gui"
path = "src/main.rs"

[dependencies]
modrix-core.workspace = true
modrix-download.workspace = true
modrix-ipc.workspace = true
modrix-service.workspace = true
iced.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rfd.workspace = true
modrix-plugin.workspace = true
modrix-registry.workspace = true
image.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
